
import java.awt.Color;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.io.Serializable;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Leonel
 */
public class TextHint extends javax.swing.JPanel implements Serializable{
    private String hint = "CampoTextHint";
    private Color gris = new Color(204,204,204);
    
    public void setHint(String texto){
        hint = texto;
        jTextField1.setText(hint);
    }
    
    public String getHint(){
        return hint;
    }
    
    
    /**
     * Creates new form TextHint
     */
    
    public enum tipoCampo {CADENA, NUMERICO};
    private tipoCampo tipo = tipoCampo.CADENA;
    
    public  void setTipoCampo (tipoCampo tipo){
        this.tipo=tipo;
    }
    
    public tipoCampo  getTipoCampo(){
        return tipo;
    }
    
    
    
    
    public TextHint() {
        initComponents();
        jTextField1.setText(hint);
        jTextField1.addFocusListener(new FocusListener() {
            @Override
            public void focusGained(FocusEvent e) {
                //Gana foco
                if(jTextField1.getText().startsWith(hint)==true){
                    jTextField1.setText("");
                    jTextField1.setForeground(Color.black);
                }
            }

            @Override
            public void focusLost(FocusEvent e) {
              //Pierde foco
              if(jTextField1.getText().equals("")==true){
                    jTextField1.setText(hint);
                    jTextField1.setForeground(gris);
                }
            }
        });
        jTextField1.addKeyListener(new KeyListener() {
            @Override
            public void keyTyped(KeyEvent e) {
                //Cuando escribes, es decir, aparece una letra en el campo de texto
                char tecla = e.getKeyChar();
                
                if(tipo == tipoCampo.NUMERICO){
                    if( (tecla<48) || (tecla>57) && (tecla!='\b') ){
                        e.consume(); //Evita el evento
                    }
                }
                
            }

            @Override
            public void keyPressed(KeyEvent e) {
                
                
            }

            @Override
            public void keyReleased(KeyEvent e) {
                
                
            }
        });
    }

   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();

        jTextField1.setForeground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
